spring:
  application:
    name: streamshield-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/streamshield}
    username: ${DB_USER:streamshield}
    password: ${DB_PASS:streamshield}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
streamshield:
  ner:
    modelId: ${NER_MODEL_ID:dslim/bert-base-NER}
    openNlpEnabled: ${OPENNLP_ENABLED:true}
  dp:
    epsilon: 1.0
  regexConfig: classpath:regexes.yml
